import React from 'react';
import { NextPage } from 'next';
import axios, { AxiosInstance } from 'axios';

import PublicShell from '../../common/PublicShell';
import { WKProfile } from '../../../types';
import { WaniKaniReviews, WaniKaniProfile, WaniKaniAccuracy } from './WaniKani.data';

// Create Axios instance.
const api: AxiosInstance = axios.create({
  baseURL: 'https://kingofboxes.mxblue.net.au:4000/',
});

const WaniKani: NextPage<WKProfile> = (data) => {
  return (
    <PublicShell title="WaniKani Progression | Justin's Website">
      <h1>WaniKani Progression</h1>
      <span>
        WaniKani is a tool for learning Japanese radicals, Kanji and vocabulary. I am currently
        learning this as a hobby and to supplement my existing knowledge of Chinese characters. The
        information below is generated by the{' '}
        <a href="https://github.com/kingofboxes/kingofboxes.github.io/blob/master/backend/controller.js">
          {' '}
          backend
        </a>{' '}
        automatically using the WaniKani v2 API.
      </span>
      <WaniKaniProfile data={data} />
      <WaniKaniReviews data={data} />
      <WaniKaniAccuracy data={data} />
    </PublicShell>
  );
};

// Fetch data before load.
WaniKani.getInitialProps = async () => {
  const res = await api.get('/wanikani');
  const data: WKProfile = res.data;
  return data;
};

export default WaniKani;
